(in-package :om)
;===============================================
;   OMishi
;   Common Lisp Functions by Yoshiaki Onishi
;   (c) 2024 by Yoshiaki Onishi.
;===============================================
; OMishi Functions: Voice and Chord-Seq Transformations (Moved from List Operations)


;===============================================

(om::defmethod! zigzag-chordseqtrace ( (chordseq list) (list2 list) (num1 number) (num2 number) (num3 number) &optional (contouroption nil))
 :initvals '('((6000 6400 6700 7000 7400 7800) (6100 6500 6800 7100 7500 7900) (6200 6600 6900 7200 7600 8000) (6300 6700 7000 7300 7700 8100)) '(3 4) 0 2 1 nil)
  :indoc '("chord-seq list of midicents" "zigzag-arithm-ser Inlet 1: sublist length(s)" "zigzag-arithm-ser Inlet 2: starting pitch in nth value" "zigzag-arithm-ser Inlet 3: skip within sublist" "zigzag-arithm-ser Inlet 4: skip from one sublist to another" "further process of each sublist")
  :icon 5678645
  :doc "Zigzag Chord-seq Trace 

(Yoshiaki Onishi, July 8, 2024)

Specifically designed for use with a chord-seq object, this function accomplishes the following:

1. Each chord within the chord-seq object is sorted pitchwise, from the lowest to the highest pitch. 
2. Inlet 1 accepts list of midicents from the chord-seq object. After each sublist is reordered from lowest to highest midicents, the chord-seq list is flattened, resembling upward arpeggios from one chord to another.
3a. Inlets 2 (list), 3~5 (number) are analogous to the *zigzag-arithm-ser* function of the OMishi Library. The parameters determine how the series of notes ought to be traversed. It does use *zigzag-arithm-ser* function, with produces the *nth* values for the flattened chord-seq list. 
3b. Inlet 6: independent from but concurrent to Inlet 2, you can specify the specific *movement* that each group of the pitch-traversing movement undergoes. Aside from nil, you have to specify it with a list.
- - - nil or (o) : sublist is read ordinarily, from beginning to end.
- - - (r): sublist is retrograded.
- - - (b1): sublist is bifurcated clockwise from its center.
- - - (b2): sublist is bifurcated counterclockwise from its center.
- - - (c1): sublist is converged from the beginning, clockwise, toward its center.
- - - (c2): sublist is converged from the end, counterclockwise, toward its center.
- - - You may combine any of these items, e.g. (o c1 r), which are read cyclically.
4. The numbers that exceed the length of the flattened chord-seq list are converted, in such a way that: (exceeding number) mod (length of the flattened chord-seq list)
5. The list generated by the preceding process will be used to read the flattened chord-seq object.

Please refer to the example patch, accessible by clicking the function and pushing t.
"
(setq   prelimsortedchordseq (loop for i in chordseq collect (sort i #'<))
        prelimsortedchordseq (flat (loop for i in prelimsortedchordseq collect i))
        prelimsortedchordseqlength (length prelimsortedchordseq)
        arithmserlength (length list2)
        longarithmserlist (flat (loop repeat (om-round (/ prelimsortedchordseqlength arithmserlength)) collect list2))
        arithms (zigzag-arithm-ser num1 longarithmserlist num2 num3)

        contouroption2  (if (or (eq contouroption nil) (eq contouroption 'o))
                            (loop repeat (length longarithmserlist) collect 'o)
                            (subseq 
                                (flat 
                                    (loop repeat (ceiling (/ (length arithms) (length contouroption)))
                                        collect contouroption)
                                ) 
                            0 (length arithms)
                            )
                        )
        arithms  (flat
                        (loop for a in arithms
                                for b in contouroption2
                            if (eq b 'o)
                                collect a
                            if (eq b 'r)
                                collect (reverse a)
                            if (eq b 'b1)
                                collect (bifurcate1 a)
                            if (eq b 'b2)
                                collect (bifurcate2 a)
                            if (eq b 'c1)
                                collect (converge1 a)
                            if (eq b 'c2)
                                collect (converge2 a)                            
                        )
                    )
        arithms         (loop for a in arithms
                            collect (keep-within-value a prelimsortedchordseqlength)
                        )

        finalresult     (loop for a in arithms
                            collect (nth a prelimsortedchordseq)
                        )
)

)

;===============================================
(om::defmethod! zigzag-chordseqtrace-v2 ( (chordseq list) (list2 list) (num1 number) (num2 number) (num3 number) (chordlistoption symbol) &optional (contouroption nil) )
 :initvals '('((6000 6400 6700 7000 7400 7800) (6100 6500 6800 7100 7500 7900) (6200 6600 6900 7200 7600 8000) (6300 6700 7000 7300 7700 8100)) 
 '(3 4) 0 2 1 'lowtohigh nil)
  :indoc '("chord-seq list of midicents" 
  "zigzag-arithm-ser Inlet 1: sublist length(s)" 
  "zigzag-arithm-ser Inlet 2: starting pitch in nth value" 
  "zigzag-arithm-ser Inlet 3: skip within sublist" 
  "zigzag-arithm-ser Inlet 4: skip from one sublist to another" 
  "if the initial chord-seq list should be sorted"
  "further process of each sublist")
  :menuins '((5 (("sort from low to high" 'lowtohigh ) ("sort from high to low" 'hightolow)("order of list as is" 'asis))))

  :icon 5678645
  :doc "Zigzag Chord-seq Trace 

(Yoshiaki Onishi, February 16 2025)

Specifically designed for use with a chord-seq object, this function accomplishes the following:

1. Each chord within the chord-seq object is sorted pitchwise, from the lowest to the highest pitch. 
2. Inlet 1 accepts list of midicents from the chord-seq object. 
3a. Inlets 2 (list), 3~5 (number) are analogous to the *zigzag-arithm-ser* function of the OMishi Library. The parameters determine how the series of notes ought to be traversed. It does use *zigzag-arithm-ser* function, with produces the *nth* values for the flattened chord-seq list. 
3b. (NEW in version 2) Inlet 6 gives options of sorting the pitches within each chord (sublist) from the lowest to the highest, from the highest to the lowest, or not sorting them and processing them in the order present in the original chord-seq list.  
3c. Inlet 7 (formerly Inlet 6 in the original version): independent from but concurrent to Inlet 2, you can specify the specific *movement* that each group of the pitch-traversing movement undergoes. Aside from nil, you have to specify it with a list.
- - - nil or (o) : sublist is read ordinarily, from beginning to end.
- - - (r): sublist is retrograded.
- - - (b1): sublist is bifurcated clockwise from its center.
- - - (b2): sublist is bifurcated counterclockwise from its center.
- - - (c1): sublist is converged from the beginning, clockwise, toward its center.
- - - (c2): sublist is converged from the end, counterclockwise, toward its center.
- - - You may combine any of these items, e.g. (o c1 r), which are read cyclically.
4. The numbers that exceed the length of the flattened chord-seq list are converted, in such a way that: (exceeding number) mod (length of the flattened chord-seq list)
5. The list generated by the preceding process will be used to read the flattened chord-seq object.

Please refer to the example patch, accessible by clicking the function and pushing t.
"
(setq   prelimsortedchordseq (loop for i in chordseq collect 
(cond   ((eq chordlistoption 'lowtohigh) (sort i #'<))
        ((eq chordlistoption 'hightolow) (sort i #'>))
        ((eq chordlistoption 'asis) i)
))
        prelimsortedchordseq (flat (loop for i in prelimsortedchordseq collect i))
        prelimsortedchordseqlength (length prelimsortedchordseq)
        arithmserlength (length list2)
        longarithmserlist (flat (loop repeat (om-round (/ prelimsortedchordseqlength arithmserlength)) collect list2))
        arithms (zigzag-arithm-ser num1 longarithmserlist num2 num3)

        contouroption2  (if (or (eq contouroption nil) (eq contouroption 'o))
                            (loop repeat (length longarithmserlist) collect 'o)
                            (subseq 
                                (flat 
                                    (loop repeat (ceiling (/ (length arithms) (length contouroption)))
                                        collect contouroption)
                                ) 
                            0 (length arithms)
                            )
                        )
        arithms  (flat
                        (loop for a in arithms
                                for b in contouroption2
                            if (eq b 'o)
                                collect a
                            if (eq b 'r)
                                collect (reverse a)
                            if (eq b 'b1)
                                collect (bifurcate1 a)
                            if (eq b 'b2)
                                collect (bifurcate2 a)
                            if (eq b 'c1)
                                collect (converge1 a)
                            if (eq b 'c2)
                                collect (converge2 a)                            
                        )
                    )
        arithms         (loop for a in arithms
                            collect (keep-within-value a prelimsortedchordseqlength)
                        )

        finalresult     (loop for a in arithms
                            collect (nth a prelimsortedchordseq)
                        )
)

)


;===============================================

(om::defmethod! voice-interpolator 
((originvoice t) (arrivalvoice t)  (order list) (numsteps number) (curve number) (tempo number) (timesig list) (maxsub number) (forbid list) (offset number) (precis number))  
 :initvals '(nil nil '((0 0)(1 1)(2 2)) 10 0.0 60 '(4 4) 8 nil 0.0 0.5) 
  :indoc '(
    "voice object with notes with which the interpolation begins (NB: number of notes must match between the beginning and ending Voice objects)" 
    "voice object with notes with which the interpolation ends (NB: number of notes must match between the beginning and ending Voice objects)" 
    "path of interpolation. Given the first note is index number 0, create list of lists denoting the connection of interpolation path from the beginning Voice object to the ending Voice object" 
    "number of steps" 
    "curve value"
     "tempo" 
     "time signature" 
     "maximum subdivision" 
     "list of forbidden subdivisions"
      "offset, gracenotes?"
       "precision 0 to 1.0")
  :icon 2345312
  :numouts 2
  :doc "voice-interpolator

(Yoshiaki Onishi, April 13, 2026)

This object interpolates, both pitches and rhythms, between two VOICE objects. 

Notes:

0. Important: because of the way OMQUANTIFY handles the quantization process, Any 'rest' at the beginning of the sequence, including departing and arriving voice, will be omitted so that the music begins on the downbeat of each bar. In the earlier version of this patch, the initial rests were retained, but it would produce incorrect, additional notes toward the end of the sequence.
1. Both VOICE objects must have the same number of notes. 
2. It can accept dyads and chords. However, such dyads and chords that are being interpolated must have the identical list length. Thus, if a dyad is interpolated, it must be interpolated into a dyad. If the number of notes in the departure and arrival varies, it is important to modify the list so that the length of the list matches. (6000 6500 7200) ==> (3800 5000 5000) 
3. There are two outlets. The one on the left connects to right inlet of MULTI-SEQ. The one on the right connects to the right inlet of POLY, or using CONCAT-SCORE-OBJS, you can connect to the 'self' inlet of VOICE.
"


(let* (
; let's define the lists of midic as well as onsets for both voices/chord-seqs. there will be four (4) of them in total:

(originlmidic (Lmidic (Objfromobjs originvoice (make-instance 'chord-seq))))
(originlonset (Lonset (Objfromobjs originvoice (make-instance 'chord-seq))))
(originlduration (Ldur (Objfromobjs originvoice (make-instance 'chord-seq))))
(arrivallmidic (Lmidic (Objfromobjs arrivalvoice (make-instance 'chord-seq))))
(arrivallonset (Lonset (Objfromobjs arrivalvoice (make-instance 'chord-seq))))
(arrivallduration (Ldur (Objfromobjs arrivalvoice (make-instance 'chord-seq))))

(lengthmidic (length originlmidic))


; first of all, we need to populate the ordered midicents out of the original rows, as well as arrival rows. Same has to be done on the onset for both ends, using the paired value indicated in "order". let these be named:
; orderedLMidicOriginal
; orderedLMidicArrival
; orderedLOnsetOriginal
; orderedLOnsetArrival
 
(orderedLMidicOriginal (loop for item in order
 collect (nth (car item) originlmidic)))
(orderedLMidicArrival (loop for item in order
 collect (nth (cadr item) arrivallmidic)))
#| 
(orderedLDurOriginal (loop for item in order
 collect (nth (car item) originlduration)))
(orderedLDurArrival (loop for item in order
 collect (nth (cadr item) arrivallduration)))
|#

(orderedLOnsetOriginal (loop for item in order
 collect (nth (car item) originlonset)))
(orderedLOnsetArrival (loop for item in order
 collect (nth (cadr item) arrivallonset)))

; Now that is done, what we need to do is to interpolate them using "interpolation" function. We need two interpolation instances:

; 1. interpolation of pitches from the origin to arrival
; 2. interpolation of onsets from the origin to arrival

; I guess the "orderedL..." must be sent through loop!!!

(interpolatedMidics   (loop for a in orderedLMidicOriginal
for b in orderedLMidicArrival
collect  (interpolation a b numsteps curve)))

#| 
(interpolatedDurs   (loop for a in orderedLDurOriginal
for b in orderedLDurArrival
collect  (interpolation a b numsteps curve)))
|#


(interpolatedOnsets (list (loop for a in orderedLOnsetOriginal
for b in orderedLOnsetArrival
collect (interpolation a b numsteps curve))))

; have to modify them so that the list outputs are the same to the OMLoop version of Interpolator

(interpolatedMidics2 (loop for a in interpolatedMidics
                          collect (loop for b in a
                                          collect (list b))))
#| 
(interpolatedDurs2  (loop for a in interpolatedDurs
                          collect (loop for b in a
                                          collect (list b))))
|#
(interpolatedOnsets2 (flat (loop for a in interpolatedOnsets
                                ;   for w in interpolatedDurs
                          collect (loop for b in a
                                      ;    for x in w
                                          collect (loop for c in b
                                                ;          for y and x
                                                        collect (list c) ))  ) 1)) 

; These two "interpolated...2" items are passed through loop again, made into individual chord-seq. These are then built into multi-seq objects.
; NOTE: this mutiSeqsOfMultiSeqsOLD is an old version where, as in the OMLoop version, it creates list of multi-seqs. Because in the combining process we will have to bring each multi-seq back to a list of chord-seq, I will dispense with the initial loop's collect function where it makes 'multi-seq.
#| 

(multiSeqsOfMultiSeqsOLD (loop for a in interpolatedMidics2
                            for b in interpolatedOnsets2
                            collect (make-instance 'multi-seq
                                                   :chord-seqs (loop for c in a
                                          for d in b
                                          collect  (make-instance 'chord-seq
                                                                  :Lmidic c
                                                                  :Lonset d
                                                                  )
                                                                     )
                                                   )
                            )
)
 |#

(multiSeqsOfMultiSeqs (loop for a in interpolatedMidics2
                            for b in interpolatedOnsets2
                         
                            collect (loop for c in a
                                          for d in b
                        
                                          collect  (make-instance 'chord-seq
                                                                  :Lmidic c
                                                                  :Lonset d
                                                                
                                                                  )
                                          )
                            )
)

;this creates the list of multi-seqs. so now we have to combine them all together. 
; first with the function arithm-ser-gen, which is to create number of steps entered using arithm-ser, except it's used as indexes, so (0 ...) etc.

(arithmSerGen (arithm-ser 0 (- numsteps 1) 1) )
(preChordSeqCombiner (loop for a in arithmSerGen
                           collect  (loop for b in multiSeqsOfMultiSeqs 
                                         collect (nth a b))
                           )
)



(chordSeqCombiner (loop for a in arithmSerGen
                        collect (reduce #'merger (nth a preChordSeqCombiner))
                        ) 
)


(ChordSeqCombiner2 (loop for a in ChordSeqCombiner
                              collect (make-instance 'chord-seq
                                                     :Lmidic (Lmidic (Objfromobjs a (make-instance 'chord-seq)))
                                                     :Lonset 
(loop for n in (Lonset (Objfromobjs a (make-instance 'chord-seq)))
    collect (- n (first (Lonset (Objfromobjs a (make-instance 'chord-seq)))))

)
                                                     :Ldur (Ldur (Objfromobjs a (make-instance 'chord-seq)))
                                                     )
                              )
)


;now these are to undergo omquantify

(quantifiedVoicesPoly (loop for aa in ChordSeqCombiner2
                        collect (omquantify aa tempo timesig maxsub forbid offset precis) 
)
)



)
; interpolatedMidics2
;  interpolatedOnsets2
; interpolatedOnsets
;interpolatedDurs2
; multiSeqsOfMultiSeqs 
; ChordSeqCombiner2

 (values chordSeqCombiner2 quantifiedVoicesPoly)

)


)

